nginx:
  build: ../images/nginx
  command: nginx -g "daemon off;"
  container_name: dev_neginx
  links:
    - php
  ports:
    - "80:80"
php:
  build: ../images/php
  container_name: dev_php
  volumes:
    - . :/var/www/html
  working_dir: /var/www/html/app/public
  command: php-fpm
  ports:
    - "9000:9000"
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    APP_KEY: SomeRandomKey!!!
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
